<a href="https://colab.research.google.com/github/SrinathNeogi/PW-Skills-Data-Science-with-Generative-AI-Course/blob/main/Numpy_Assignment_Solution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Q1
import numpy as np

In [ ]:
#Q2
arr = np.array([1,2,3,4,5])
print(arr.dtype)

int64


In [ ]:
#Q3
arr = np.array([1.5, 2.6, 3.7])
if arr.dtype == float:
    print("True")
else:
    print("False")

True


In [ ]:
#Q4
arr1 = np.array([1+2j , 2+3j, 3+4j])
print(arr1,"\n", arr1.dtype)

[1.+2.j 2.+3.j 3.+4.j] 
 complex128


In [ ]:
#Q5
arr = np.array([1.5, 2.6, 3.7])
arr = arr.astype(int)
print(arr,arr.dtype)

[1 2 3] int64


In [ ]:
#Q6, 7
arr = np.random.randint(1,5, size = (5))
print(arr)
def info(arr1):
    print(f"Shape = {arr.shape} , Size = {arr.size} , Dimension = {arr.ndim} = , DataType = {arr.dtype}")

info(arr)

[3 2 1 1 2]
Shape = (5,) , Size = 5 , Dimension = 1 = , DataType = int64


In [ ]:
#Q8
def item_size_info(arr):
    item_size = arr.itemsize
    size = arr.nbytes

    return item_size , size

arr = np.random.randint(1,5 , (1))

item_size , size = item_size_info(arr)

print(f"item size = {item_size} , size = {size} bytes")

item size = 8 , size = 8 bytes


In [ ]:
#Q9
def array_strides(arr):
    return arr.strides

strides = array_strides(np.array([[1,2,3],[4,5,6]]))
print(strides)
print(arr.dtype)

(24, 8)
int64


In [ ]:
#Q10
def array_strides_shape(arr):
    print(f"strides = {arr.strides}")
    print(f"Shape = {arr.shape}")

arr = np.array([[1,2,3] , [4,5,6]])
array_strides_shape(arr)

strides = (24, 8)
Shape = (2, 3)


In [ ]:
#Q11
import numpy as np
def create_zeros_array(n):
    return np.zeros(n)

n = int(input())
arr = create_zeros_array(n)

print(arr)

5
[0. 0. 0. 0. 0.]


In [ ]:
#Q12
def zero_mat(row , col):
    return np.zeros((row,col))

row = int(input())
col = int(input())

mat = zero_mat(row , col)
print(mat)

5
5
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
#Q13
def generate_range_array(start , stop , step):
    return np.arange(start, stop, step)

start = int(input("start "))
stop = int(input("stop "))
step = int(input("step "))

arr = generate_range_array(start, stop, step)
print(arr)

start 1
stop 10
step 2
[1 3 5 7 9]


In [ ]:
#Q14
def generate_linear_space(start , stop , num):
    return np.linspace(start , stop , int(num))

start = float(input("start "))
stop = float(input("stop "))
step = int(input("step "))

arr = generate_linear_space(start , stop , step)
print(arr)

start 1
stop 10
step 5
[ 1.    3.25  5.5   7.75 10.  ]


In [ ]:
#Q15
def mat_eye(n):
    return np.eye(n,n , dtype=int)

n = int(input())
arr = mat_eye(n)

print(arr)

3
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
#Q16
import numpy as np
def list_to_array(l1):
    return np.asarray(l1)

l1 = [1,2,3,4,5]

arr = list_to_array(l1)

print(arr , type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [ ]:
#Q17
arr = np.array([1,2,3,4,5,6])
print(arr)
arr1 = arr.view(dtype = np.int8) # Previously every integer was of 8 bytes, with np.int8 every integer is given 1 bytes
print(arr1)
print(f"Total size = {arr1.nbytes} bytes")
print(f"Bytes per item = {arr1.itemsize} byte")

[1 2 3 4 5 6]
[1 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 4 0 0 0 0 0 0 0 5 0 0 0 0
 0 0 0 6 0 0 0 0 0 0 0]
Total size = 48 bytes
Bytes per item = 1 byte


In [ ]:
#Q18
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

print(np.concatenate((arr1 , arr2)))

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
#Q19
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[1,2,3,4],[5,6,7,8]])

print(np.concatenate((arr1,arr2),1))

[[1 2 3 1 2 3 4]
 [4 5 6 5 6 7 8]]


In [ ]:
#Q20
def vertical_stack(list_arrays):
    return np.vstack(list_arrays)

arr1 = np.array([[1,2,3] , [4,5,6]])
arr2 = np.array([[1,2,3]])
arr3 = np.array([[7,8,9]])

arr_final = vertical_stack([arr1,arr2,arr3])

print(arr_final)

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [7 8 9]]


In [ ]:
#Q21
def array_range(start , stop , step):
    return np.arange(start , stop , step)

start = int(input("Start = "))
stop = int(input("Stop = "))
step = int(input("Step = "))

arr = array_range(start , stop , step)

print(arr)

Start = 1
Stop = 10
Step = 2
[1 3 5 7 9]


In [ ]:
#Q22
def equally_spaced_array():
    return np.linspace(0,1,10)

arr = equally_spaced_array()
print(arr)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [ ]:
#Q23
def log_spaced():
    return np.logspace(0,3,5)
    #10^0 to 10^3 .....5 values. Here by default base = 10
arr = log_spaced()

print(arr)

[   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [ ]:
#Q24
import numpy as np
import pandas as pd
mat = np.random.randint(1,100, (5,3))
print(f"Array {mat}")
df = pd.DataFrame(mat)
print(f"Data Frame = \n{df}")

Array [[84 21 15]
 [90 81 66]
 [13 17 27]
 [30 23 70]
 [41  5 90]]
Data Frame = 
    0   1   2
0  84  21  15
1  90  81  66
2  13  17  27
3  30  23  70
4  41   5  90


In [ ]:
#Q25
def negative_to_zero(df, col):
    if col in df.columns:
        df[col] = np.where(df[col]<0 , 0, df[col])
        print(f"Updated DataFrame = \n{df}")
    else:
        print(f"{col} not present in {df}")

df = pd.DataFrame([[1,2,3],[5,-6,7]])
col = 2

negative_to_zero(df,col)

Updated DataFrame = 
   0  1  2
0  1  2  3
1  5 -6  7


In [ ]:
#Q26
arr = np.array([10,20,30,40,50])

arr[2]

30

In [ ]:
#Q27
arr_2d = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
arr_2d[1,2]

6

In [ ]:
#Q28
arr = np.array([3, 8, 2, 10, 5, 7])
arr[arr > 5]

array([ 8, 10,  7])

In [ ]:
#Q29
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[2:6]

array([3, 4, 5, 6])

In [ ]:
#Q30
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2d[0:2 , 1:3]

array([[2, 3],
       [5, 6]])

In [ ]:
#Q31
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arrindx = np.array([0,1])

for i in arrindx:
    print(arr2d[i])

[1 2 3]
[4 5 6]


In [ ]:
#Q32
arr = np.array([1,2,3,4,5,6,7,8,9,10])
threshold = 4
arr[arr>threshold]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
#Q33
arr3d = np.random.randint(1,100, size = [3,3,3])
print(f"3D array = \n{arr3d}")
arr0 = np.array([0,1,2])
arr1 = np.array([1,2])
arr2 = np.array([0,1])

for i in arr0:
    for j in arr1:
        for k in arr2:
            print(f"{i} row {j} column {k} height = {arr3d[i,j,k]}")

3D array = 
[[[15 86  4]
  [32 32 32]
  [95 11 46]]

 [[22 45 27]
  [ 4 53 54]
  [49 61 17]]

 [[ 6 13 22]
  [25  6  9]
  [67 78 92]]]
0 row 1 column 0 height = 32
0 row 1 column 1 height = 32
0 row 2 column 0 height = 95
0 row 2 column 1 height = 11
1 row 1 column 0 height = 4
1 row 1 column 1 height = 53
1 row 2 column 0 height = 49
1 row 2 column 1 height = 61
2 row 1 column 0 height = 25
2 row 1 column 1 height = 6
2 row 2 column 0 height = 67
2 row 2 column 1 height = 78


In [ ]:
#Q34
arr = np.array([1,2,3,4,5,6,7])
print(arr[(arr>2) & (arr<6)])

[3 4 5]


In [ ]:
#Q35
def access2d(arr , row , col):
    return arr[row,col]
    # arr[1,0] then arr[2,1]
    #Both values are stores in an array.

row = np.array([1,2])
col = np.array([0,1])

arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

op = access2d(arr2d , row , col)

print(op)



[4 8]


In [ ]:
#Q36
import numpy as np
arr = np.random.randint(1,5 , (3,3))
print(f"arr = \n{arr} \n arr + 5 after broadcasting = \n{arr+5}")

arr = 
[[2 4 2]
 [2 3 1]
 [1 3 1]] 
 arr + 5 after broadcasting = 
[[7 9 7]
 [7 8 6]
 [6 8 6]]


In [ ]:
#Q37
arr1 = np.random.randint(1,5 , (1,3))
arr2 = np.random.randint(1,5 , (4,3))
print(f"{arr1} \n\n {arr2} \n\n")
print(arr1*arr2)

[[3 3 2]] 

 [[1 4 1]
 [1 3 2]
 [1 1 4]
 [4 2 1]] 


[[ 3 12  2]
 [ 3  9  4]
 [ 3  3  8]
 [12  6  2]]


In [ ]:
#Q38
arr1 = np.random.randint(1,5 , (1,4))
arr2 = np.random.randint(1,5 , (4,3))
print(f"{arr1} \n\n {arr2}\n\n")
# print(arr2 + arr1) -> Gives value error
arr1 = arr1.reshape((4,1))
result = arr2 + arr1
print(f"{arr2} \n + \n{arr1} = \n\n")
print(result)

[[2 2 4 2]] 

 [[3 4 1]
 [4 3 1]
 [2 4 3]
 [4 1 2]]


[[3 4 1]
 [4 3 1]
 [2 4 3]
 [4 1 2]] 
 + 
[[2]
 [2]
 [4]
 [2]] = 


[[5 6 3]
 [6 5 3]
 [6 8 7]
 [6 3 4]]


In [ ]:
#Q39
arr1 = np.random.randint(1,5 , (1,3))
arr2 = np.random.randint(1,5 , (3,1))
print(f"{arr1} \n\n {arr2}\n\n")

print(arr1 + arr2)

[[2 4 2]] 

 [[1]
 [4]
 [3]]


[[3 5 3]
 [6 8 6]
 [5 7 5]]


In [ ]:
#Q40
import numpy as np
arr1 = np.random.randint(1,5 , (2,3))
arr2 = np.random.randint(1,5 , (2,2))
print(f"{arr1} \n\n {arr2}\n\n")
try:
    result = arr1*arr2
except ValueError as e:
    print(e)


[[2 3 4]
 [1 2 2]] 

 [[4 1]
 [4 4]]


operands could not be broadcast together with shapes (2,3) (2,2) 


In [ ]:
#Q41
arr = np.array([[1, 2, 3], [4, 5, 6]])
col_mean = np.mean(arr , axis=0)
print(col_mean)

[2.5 3.5 4.5]


In [ ]:
#Q42
arr = np.array([[1, 2, 3], [4, 5, 6]])
max_row = np.max(arr , axis=1)
print(max_row)

[3 6]


In [ ]:
#Q43
arr = np.array([[1, 2, 3], [4, 5, 6]])
max_col = np.max(arr , axis=0)
print(max_col)

[4 5 6]


In [ ]:
#Q44
arr = np.array([[1, 2, 3], [4, 5, 6]])
sum_row = np.sum(arr , axis=1)
print(sum_row)

[ 6 15]


In [ ]:
#Q45
arr = np.array([[2,4,6],[3,5,7]])
sum_col = np.sum(arr , axis=0)
print(sum_col)

count = 0
for i in sum_col:
    if i % 2 == 0:
        print(f"{count} column all elements are even.")
    else:
        print(f"{count} column all elements are not even.")
    count = count+1

[ 5  9 13]
0 column all elements are not even
1 column all elements are not even
2 column all elements are not even


In [ ]:
#Q46
original_array = np.array([1, 2, 3, 4, 5, 6])

reshaped_array = original_array.reshape((2,-1))

print(reshaped_array)

[[1 2 3]
 [4 5 6]]


In [ ]:
#Q47
def flatten_array(arr):
    return  arr.flatten()

input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

flattered_array = flatten_array(input_matrix)

print(flattered_array)

[1 2 3 4 5 6]


In [ ]:
#Q48
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

result = np.concatenate((array1,array2), axis = 1)
print(result)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
#Q49
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

def splitter(arr):
    return np.split(arr , 3 , axis=0)

subarrays = splitter(original_array)

for subarray in subarrays:
    print(subarray)

[[1 2 3]]
[[4 5 6]]
[[7 8 9]]


In [ ]:

#axis=1 → Row-wise operation (sum along columns, producing one value per row).
#axis=0 → Column-wise operation (sum along rows, producing one value per column).
#Write it down

In [ ]:
#Q50
import numpy as np
def insert_delete(arr, index_insert , value , index_delete):
    temp = 0
    for index in index_insert:
        arr = np.insert(arr , index , value[temp])
        print(f"After inserting {value[temp]} at index {index} array is = {arr}")
        temp = temp+1

    for index in index_delete:
        arr = np.delete(arr , index)
        print(f"Index {index} element is deleted. Array is {arr}")


original_array = np.array([1, 2, 3, 4, 5])

indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

insert_delete(original_array , indices_to_insert , values_to_insert , indices_to_delete)

After inserting 10 at index 2 array is = [ 1  2 10  3  4  5]
After inserting 11 at index 4 array is = [ 1  2 10  3 11  4  5]
Index 1 element is deleted. Array is [ 1 10  3 11  4  5]
Index 3 element is deleted. Array is [ 1 10  3  4  5]


In [ ]:
#Q51
arr1 = np.random.randint(1,10 , size = (5))
arr2 = np.random.randint(1,10 , size = (5))

print(f"{arr1} + {arr2} = {arr1+arr2}")

[7 1 5 5 2] + [3 7 4 6 4] = [10  8  9 11  6]


In [ ]:
#Q52
arr1 = np.arange(10,1,-1)

arr2 = np.arange(1,10,1)

print(f"{arr1} - {arr2} = {arr1-arr2}")

[10  9  8  7  6  5  4  3  2] - [1 2 3 4 5 6 7 8 9] = [ 9  7  5  3  1 -1 -3 -5 -7]


In [ ]:
#Q53
arr1 = np.random.random_sample(5)
arr2 = np.random.randint(1,5,5)
print(arr1*arr2)

[1.82403335 0.34726288 1.18469334 3.26323036 0.44792967]


In [ ]:
#Q54
arr1 = np.arange(2,10 , 2)
arr2 = np.arange(1,5,1)
print(arr1,arr2)
print(arr1/arr2)

[2 4 6 8] [1 2 3 4]
[2. 2. 2. 2.]


In [ ]:
#Q55
arr1 = np.arange(1,5,1)
arr2 = arr1[::-1]
print(arr1,arr2)
print(arr1**arr2)

[1 2 3 4] [4 3 2 1]
[1 8 9 4]


In [ ]:
#Q56
def count_string(strings , substring):
    indices = np.char.count(strings, substring)

    print(indices)
    count = np.count_nonzero(indices==1)

    print(f"Count of {substring} is {count}")


arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

count_string(arr, "hello")

[1 0 1 0 1]
Count of hello is 3


In [ ]:
#Q57
import numpy as np

def array_uppercase(strings):
    return np.char.upper(strings)

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

strings_arr = array_uppercase(arr)
print(strings_arr)

['HELLO' 'WORLD' 'OPENAI' 'GPT']


In [ ]:
#Q58
def replace(arr):
    return np.char.replace(arr , "apple" , "Srinath")

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

print(replace(arr))

['Srinath' 'banana' 'grape' 'pineSrinath']


In [ ]:
#Q59
def concate_string_arr(arr1 , arr2):
    return np.char.add(arr1 , arr2)
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

result = concate_string_arr(arr1 , arr2)
print(result)

['HelloOpen' 'WorldAI']


In [ ]:
#Q60
def longest_string(arr):
    lengths = np.char.str_len(arr)

    return np.max(lengths)

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

max = longest_string(arr)

print(max)

9


In [ ]:
#Q61
arr = np.random.randint(1,1000,100)
mean = np.mean(arr)
median = np.median(arr)
variance = np.var(arr)
sd = np.std(arr)
print(f"Mean = {mean}\nMedian = {median}\nVariance = {variance}\nStandard Deviation = {sd}")

Mean = 497.73
Median = 513.5
Variance = 84737.07710000001
Standard Deviation = 291.0963364592554


In [ ]:
#Q62
arr = np.random.randint(1,100, 50)

percentile_25 = np.percentile(arr , 25)
percentile_75 = np.percentile(arr , 75)

print(f"25%ile = {percentile_25}\n75%ile  ={percentile_75}")

25%ile = 19.0
75%ile  =71.25


In [ ]:
#Q63
arr1 = np.random.randint(1,10,5)
arr2 = np.random.randint(1,5,5)

print(np.corrcoef(arr1,arr2))

[[1.         0.10206207]
 [0.10206207 1.        ]]


In [ ]:
#Q64
arr1 = np.random.randint(1,10,(2,3))
arr2 = np.random.randint(1,5,(3,2))

prod = np.dot(arr1,arr2)

print(prod)

[[32 17]
 [18 12]]


In [ ]:
#Q65
random_array = np.random.randint(10, 1001, 50)

percentile_10 = np.percentile(random_array, 10)
percentile_50 = np.percentile(random_array, 50)  # Median
percentile_90 = np.percentile(random_array, 90)

# Calculate quartiles
q1 = np.percentile(random_array, 25)  # First quartile
q3 = np.percentile(random_array, 75)  # Third quartile

print("10th percentile:", percentile_10)
print("50th percentile (Median):", percentile_50)
print("90th percentile:", percentile_90)
print("First quartile (Q1):", q1)
print("Third quartile (Q3):", q3)

10th percentile: 129.60000000000002
50th percentile (Median): 562.0
90th percentile: 925.2
First quartile (Q1): 255.0
Third quartile (Q3): 779.75


In [ ]:
#Q66
arr = np.random.randint(1,10,10)
print(arr)
index = np.where(arr == 6)[0]
# Returns an array containing all indices of specified element and with [0] we will get the first occurrence
print(index)

[8 1 6 9 2 3 1 2 8 7]
[2]


In [ ]:
#Q67
arr = np.array([3,5,6,2,1,4,9])

arr_sorted = np.sort(arr)

print(arr_sorted)

[1 2 3 4 5 6 9]


In [ ]:
#Q68
arr = np.array([12, 25, 6, 42, 8, 30])
arr[arr > 20]

array([25, 42, 30])

In [ ]:
#Q69
arr = np.array([1, 5, 8, 12, 15])
arr[arr%3 == 0]

array([12, 15])

In [ ]:
#Q70
arr = np.array([10, 20, 30, 40, 50])
arr1 = arr[arr>=20]
arr2 = arr1[arr1<=40]
print(arr2)

[20 30 40]


In [ ]:
#Q71
arr = np.array([1, 2, 3])
byte_order = arr.dtype.byteorder
print(byte_order) # little endian

=


In [ ]:
#Q72
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='>i4')  # Big-endian
arr.byteswap(True)  # Swaps in-place
print(arr.dtype.byteorder)  # Output: little

>


In [ ]:
#Q73
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='>i4')  # Big-endian
new_arr = arr.newbyteorder('<')  # Create a new array with little-endian
print(new_arr.dtype.byteorder)  # Output: little

<


In [ ]:
#Q74
import numpy as np

arr = np.array([1, 2, 3, 4])

if arr.dtype.byteorder == '>':  # If big-endian
    new_arr = arr.newbyteorder('<')  # Convert to little-endian
else:
    new_arr = arr.copy()  # No need to swap

print(new_arr.dtype.byteorder)

=


In [ ]:
#Q75
import numpy as np
import sys
arr = np.array([1, 2, 3, 4])

if arr.dtype.byteorder != sys.byteorder:
    print("Byte swapping is necessary.")
else:
    print("Byte swapping is not necessary.")

Byte swapping is necessary.


In [ ]:
#Q76
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
copy_arr = arr1.copy()

copy_arr[0] = 10

print(arr1)  # Original array remains unchanged
print(copy_arr)

[1 2 3 4 5]
[10  2  3  4  5]


In [ ]:
#Q77
import numpy as np

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
view_slice = matrix[1:, 1:]

view_slice[0, 0] = 100

print(matrix)  # Original matrix is modified
print(view_slice)

[[  1   2   3]
 [  4 100   6]
 [  7   8   9]]
[[100   6]
 [  8   9]]


In [ ]:
#Q78
import numpy as np

array_a = np.arange(1, 13).reshape(4, 3)
view_b = array_a[1:]

view_b += 5

print(array_a)  # Original array is modified

[[ 1  2  3]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [ ]:
#Q79
import numpy as np

orig_array = np.arange(1, 9).reshape(2, 4)
reshaped_view = orig_array.reshape(4, 2)

reshaped_view[0, 0] = 100

print(orig_array)  # Original array is modified
print(reshaped_view)

[[100   2   3   4]
 [  5   6   7   8]]
[[100   2]
 [  3   4]
 [  5   6]
 [  7   8]]


In [ ]:
#Q80
import numpy as np

data = np.random.randint(1, 10, (3, 4))
data_copy = data[data > 5].copy()

data_copy[0] = 100

print(data)  # Original data is unchanged
print(data_copy)

[[8 6 8 2]
 [4 8 8 3]
 [4 6 3 8]]
[100   6   8   8   8   6   8]


In [ ]:
#Q81
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

sum_matrix = A + B
diff_matrix = A - B

print(sum_matrix)
print(diff_matrix)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]


In [ ]:
#Q82
import numpy as np

C = np.array([[1, 2], [3, 4], [5, 6]])
D = np.array([[7, 8, 9, 10], [11, 12, 13, 14]])

product = np.dot(C, D)
print(product)

[[ 29  32  35  38]
 [ 65  72  79  86]
 [101 112 123 134]]


In [ ]:
#Q83
import numpy as np

E = np.array([[1, 2, 3], [4, 5, 6]])
transpose_E = E.T

print(transpose_E)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
#Q84
import numpy as np

F = np.array([[1, 2], [3, 4]])
det_F = np.linalg.det(F)

print(det_F)

-2.0000000000000004


In [ ]:
#Q85
import numpy as np

# Create a square matrix G
G = np.array([[1, 2], [3, 4]])

# Find the inverse of G
inverse_G = np.linalg.inv(G)

print(inverse_G)

[[-2.   1. ]
 [ 1.5 -0.5]]
